development:
  adapter: postgresql
  encoding: unicode
  database: image_search_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: image_search_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: image_search_production
  pool: 5
